#!/usr/bin/env python3
from pathlib import Path
import re,sys
R=Path(__file__).resolve().parents[1]
g=(R/'contracts/ProofHaltGuardian.sol').read_text()
v=(R/'contracts/DemoVault.sol').read_text()
p=(R/'contracts/proofhalt.py').read_text()
d=(R/'contracts/studionet_demo_target.py').read_text()
checks=[]
def ck(name, cond):
    if not cond: raise AssertionError(name)
    checks.append(name); print(f"PASS {len(checks):02d} {name}")
ck('Guardian exact Solidity pin', 'pragma solidity 0.8.36;' in g)
ck('Vault exact Solidity pin', 'pragma solidity 0.8.36;' in v)
ck('Guardian immutable authority', 'immutable proofHaltAuthority' in g)
ck('Guardian immutable target', 'immutable protectedTarget' in g)
ck('Guardian nonzero target code check', '.code.length' in g)
ck('Guardian onlyProofHalt modifier', 'modifier onlyProofHalt' in g)
ck('Guardian halt is authority gated', 'pauseFromProofHalt' in g and 'onlyProofHalt' in g)
ck('Guardian restore is authority gated', 'restoreFromProofHalt' in g and 'onlyProofHalt' in g)
ck('Guardian tracks active halt count', 'activeHaltCount' in g)
ck('Guardian incident active view', 'isIncidentActive' in g)
ck('Guardian incident restored view', 'isIncidentRestored' in g)
ck('Guardian decision binding view', 'incidentDecisionBinding' in g)
ck('Guardian decision binding validated', 'InvalidDecisionBinding' in g and 'decisionBinding' in g)
ck('Guardian incident state view', 'incidentState' in g)
ck('Guardian replay map', 'actionExecuted' in g)
ck('Guardian incident hash helper', 'incidentHashOf' in g)
ck('Guardian no delegatecall', 'delegatecall' not in g.lower())
ck('Guardian no callcode', 'callcode' not in g.lower())
ck('Guardian no selfdestruct', 'selfdestruct' not in g.lower())
ck('Guardian no tx.origin', 'tx.origin' not in g.lower())
ck('Guardian no assembly', re.search(r'\bassembly\b',g) is None)
ck('Guardian no arbitrary execute function', re.search(r'function\s+(execute|call|arbitraryCall)\b',g) is None)
ck('Vault one-time ProofHalt configuration', 'isProofHaltConfigured' in v)
ck('Vault Guardian binding', 'proofHaltGuardian' in v)
ck('Vault pause entrypoint', 'proofHaltPause' in v)
ck('Vault restore entrypoint', 'proofHaltRestore' in v)
ck('Vault onlyGuardian modifier', 'modifier onlyProofHaltGuardian' in v or 'modifier onlyGuardian' in v)
ck('Vault paused deposit gate', 'paused' in v and 'deposit' in v)
ck('Vault paused withdrawal gate', 'withdraw' in v and 'paused' in v)
ck('Vault reentrancy guard', 'nonReentrant' in v or 'locked' in v)
ck('Vault demo exploit bounded constant', 'DEMO_MAX_EXPLOIT_PER_CALL' in v)
ck('Vault demo exploit patch flag', 'demoExploitEnabled' in v)
ck('Vault patch function', 'applyDemoPatch' in v)
ck('Vault no delegatecall', 'delegatecall' not in v.lower())
ck('Vault no selfdestruct', 'selfdestruct' not in v.lower())
ck('Vault no tx.origin', 'tx.origin' not in v.lower())
ck('Vault no force restore admin', re.search(r'force(Unpause|Restore)|owner(Unpause|Restore)',v,re.I) is None)
ck('GenLayer dependency header', '# { "Depends": "py-genlayer:test" }' in p or 'Depends' in p[:500])
ck('GenLayer EVM interface declared', '@gl.evm.contract_interface' in p)
ck('Python incident-specific active view ABI', 'isIncidentActive' in p)
ck('Python incident-specific restored view ABI', 'isIncidentRestored' in p)
ck('Python nondeterministic consensus path', 'run_nondet_unsafe' in p)
ck('Python web evidence retrieval', 'gl.nondet.web.get' in p)
ck('Python hash verification', 'hash_matches_submitted' in p)
ck('Python evidence set commitment', 'PROOFHALT_EVIDENCE_SET_V2' in p)
ck('Python verdict digest domain', 'PROOFHALT_VERDICT_V2' in p)
ck('Python source-group inflation defense', 'hash_verified_relevant_evidence_count' in p)
ck('Python technical-anchor binding', 'technical_anchor_evidence_id' in p)
ck('Python recovery-specific schema', 'REMEDIATION_SCHEMA' in p)
ck('Python no owner force halt', re.search(r'def\s+(force_halt|admin_halt|owner_halt)',p) is None)
ck('Python no owner force restore', re.search(r'def\s+(force_restore|admin_restore|owner_restore)',p) is None)
ck('Python append-only verdict history surface', 'incident_revisions' in p and 'verdicts' in p)
ck('Python exact-host source policies', 'exact_host' in p and 'PH_SOURCE_NOT_AUTHORIZED' in p)
ck('Python immutable snapshot host policy', 'snapshot_hosts' in p and 'PH_SNAPSHOT_HOST_NOT_AUTHORIZED' in p)
ck('Python verdict-to-Guardian decision binding', 'decision_binding_hash' in p and 'bytes.fromhex' in p)
ck('Authorization-only mode disclosed', 'AUTHORIZATION_ONLY' in p and 'external_enforcement_supported' in p)
ck('Authorization-only mode never emits EVM action', 'if self.authorization_only:' in p and 'PH_ENFORCEMENT_UNAVAILABLE' in p)
ck('Studionet demo target accepts no assets', 'accepts_assets' in d and 'simulate_unauthorized_withdrawal' in d)
assert len(checks)==58
print('SUMMARY 58/58 PASS')
