#!/usr/bin/env python3
import json,re
from pathlib import Path
R=Path(__file__).resolve().parents[1]
h=(R/'site/index.html').read_text(); c=(R/'site/assets/styles.css').read_text(); j=(R/'site/assets/app.js').read_text(); s=(R/'site/src/genlayer-client.js').read_text(); b=(R/'site/assets/genlayer-client.js').read_text(); hd=(R/'site/_headers').read_text(); n=(R/'netlify.toml').read_text(); p=json.loads((R/'package.json').read_text())
checks=[]
def ck(name,cond):
    if not cond: raise AssertionError(name)
    checks.append(name); print(f'PASS {len(checks):02d} {name}')
ck('HTML doctype',h.lower().startswith('<!doctype html>'))
ck('viewport metadata','name="viewport"' in h)
ck('meta description','name="description"' in h)
ck('ProofHalt title','<title>ProofHalt' in h)
ck('local stylesheet','assets/styles.css' in h)
ck('module application script','type="module" src="assets/app.js"' in h)
ck('local SVG logo','assets/proofhalt-logo.svg' in h)
ck('GitHub source link','github.com/haris4587/ProofHalt' in h)
ck('MetaMask connection control','Connect MetaMask' in h and "method:'eth_requestAccounts'" in j)
ck('Studionet chain binding','61999' in j and 'wallet_switchEthereumChain' in j)
ck('GenLayer SDK exactly pinned',p['dependencies'].get('genlayer-js')=='1.1.8')
ck('local GenLayer browser bundle',"from './genlayer-client.js'" in j and len(b)>100_000)
ck('public contract read',"'get_global_constitution'" in s and 'readGlobalConstitution' in j)
ck('wallet-backed SDK write','createClient({ chain: studionet, account, provider })' in s)
ck('zero-value transaction','value: 0n' in s)
ck('wallet lifecycle event',"state: 'wallet'" in s)
ck('submitted lifecycle event',"state: 'submitted'" in s)
ck('consensus lifecycle event',"state: 'consensus'" in s)
ck('finalized lifecycle event',"state: 'finalized'" in s)
ck('execution result checked','ExecutionResult.FINISHED_WITH_RETURN' in s)
ck('register protocol frontend action','data-action="register_protocol"' in h and 'register_protocol:' in j)
ck('activation frontend action','data-action="activate_protocol"' in h and 'activate_protocol:' in j)
ck('constitution publication action','data-action="publish_constitution"' in h and 'publish_constitution:' in j)
ck('pending constitution activation action','data-action="activate_pending_constitution"' in h and 'activate_pending_constitution:' in j)
ck('open incident action','data-action="open_incident"' in h and 'open_incident:' in j)
ck('evidence submission action','data-action="submit_evidence"' in h and 'submit_evidence:' in j)
ck('incident adjudication action','data-action="adjudicate_incident"' in h and 'adjudicate_incident:' in j)
ck('target patch action','data-action="apply_target_patch"' in h and 'apply_one_way_patch' in j)
ck('remediation submission action','data-action="submit_remediation"' in h and 'submit_remediation:' in j)
ck('remediation adjudication action','data-action="adjudicate_remediation"' in h and 'adjudicate_remediation:' in j)
ck('incident and verdict readback',"'get_incident'" in j and "'get_latest_verdict'" in j)
ck('immutable evidence hashing','crypto.subtle.digest' in j and 'canonicalize' in j)
ck('no automatic write on page load','submitAndFinalize(' in j and j.rstrip().endswith('refreshPublicRecord();'))
ck('no token approval surface',all(x not in j+s+h for x in ('eth_sendToken','approve(address','setApprovalForAll','wallet_sendCalls')))
ck('no Snap request',all(x not in j+s for x in ('wallet_getSnaps','wallet_requestSnaps','genlayer-wallet-plugin','walletClient.connect')))
ck('authorization-only Studio disclosure','AUTHORIZATION-ONLY ON STUDIO' in h and 'without claiming a target was paused' in h)
ck('transaction safety disclosure','No token approvals. No asset transfers. No automatic writes.' in h)
ck('public end-to-end record UI','PUBLIC END-TO-END RECORD' in h and 'refreshPublicRecord' in j)
ck('responsive CSS','@media' in c)
ck('restricted CSP',"script-src 'self'" in hd and 'https://studio.genlayer.com' in hd)
ck('Netlify production build','command = "npm run build"' in n and 'publish = "site"' in n)
assert len(checks)==41
print('SUMMARY 41/41 PASS')
